open-cluster-management-io/managed-serviceaccount

.github/workflows/go-postsubmit.yml
=> gh-action: post submit

Makefile
=> Makefile: Fixes image registry

.github/workflows/go-release.yml
=> gh-action: release

.github/workflows/go-release.yml
=> Fixes gh action release

charts/managed-serviceaccount/Chart.yaml, charts/managed-serviceaccount/values.yaml
=> Chore: Bump v0.1.0 for helm charts

cmd/agent/main.go, pkg/addon/agent/health/lease.go
Closes https://github.com/open-cluster-management-io/managed-serviceaccount/issues/15
=> switch health lease to primarily managed cluster side

cmd/manager/main.go
=> update default value of agent-image-name org to open-cluster-management

.github/workflows/go-presubmit.yml, e2e/e2e_test.go, e2e/ephemeral_identity/e2e_test.go, e2e/ephemeral_identity/ephemeral_identity.go
=> add e2e for ephemeral-identity

hack/demo/demo-magic, hack/demo/ephemeral-identity/demo, hack/demo/ephemeral-identity/templates/managedclusteraddon.yaml, hack/demo/ephemeral-identity/templates/managedserviceaccount.yaml
add a simple demo for the emphemeral-identity feature
=> add demo script for ephemeral-identity feature

e2e/token/token.go
related to https://github.com/open-cluster-management-io/managed-serviceaccount/issues/14
=> add test to validate deletion of managedserviceaccount

cmd/agent/main.go, cmd/manager/main.go, e2e/framework/scheme.go
Signed-off-by: Nathan Weatherly <nweather@redhat.com>
=> add error catches

api/v1alpha1/managedserviceaccount_types.go, charts/managed-serviceaccount/crds/authentication.open-cluster-management.io_managedserviceaccounts.yaml, config/crd/bases/authentication.open-cluster-management.io_managedserviceaccounts.yaml
Signed-off-by: Nathan Weatherly <nweather@redhat.com>
=> typo fix and description review

.github/workflows/go-release.yml
this pulll adds a helm chart package upon publishing github releases
=> Github-action: Chart package action

Dockerfile
Signed-off-by: xuezhaojun <zxue@redhat.com>
=> Replace dockerfile image

pkg/addon/manager/addon.go, pkg/addon/manager/ephemeral_identity_controller.go
=> fix minior go-staticcheck issue

pkg/addon/agent/controller/token.go
Signed-off-by: Yang Le <yangle@redhat.com>
=> refresh token until remaining lifetime < 20% validity

cmd/manager/main.go, pkg/addon/agent/controller/token.go, pkg/addon/agent/controller/token_test.go, pkg/addon/manager/addon_test.go, pkg/addon/manager/ephemeral_identity_controller.go, pkg/addon/manager/ephemeral_identity_controller_test.go, pkg/controllers/event/secret_test.go, pkg/controllers/event/serviceaccount_test.go
The related issue: https://github.com/open-cluster-management-io/community/issues/167
Signed-off-by: Yang Le <yangle@redhat.com>
=> add more unit test cases

.github/workflows/go-postsubmit.yml, .github/workflows/go-presubmit.yml, .github/workflows/go-release.yml, Dockerfile, go.mod
Signed-off-by: zhujian <jiazhu@redhat.com>
=> Bump go version to 1.19

.github/workflows/go-presubmit.yml, charts/managed-serviceaccount/templates/clustermanagementaddon.yaml, charts/managed-serviceaccount/templates/clusterrole.yaml, charts/managed-serviceaccount/values.yaml, cmd/manager/main.go, e2e/install/install.go, pkg/addon/manager/manifests/templates/deployment.yaml
Signed-off-by: Wei Liu <liuweixa@redhat.com>
=> support addon deployment config

charts/managed-serviceaccount/templates/clusterrole.yaml
Signed-off-by: Wei Liu <liuweixa@redhat.com>
=> use fine grained rbac for addon

.github/workflows/go-postsubmit.yml, .github/workflows/go-release.yml
Fix: https://github.com/open-cluster-management-io/managed-serviceaccount/issues/62
=> upgrade image builder

.github/workflows/go-presubmit.yml, charts/managed-serviceaccount/templates/addondeploymentconfig.yaml, charts/managed-serviceaccount/templates/clustermanagementaddon.yaml, e2e/framework/framework.go, e2e/install/install.go, e2e/install/template_install.go, e2e/token/token.go, e2e/token/token_v1alpha1.go, go.mod, go.sum
addon an addonDeploymentConfig for template type deploying, so the managedClusterAddon.spec.installNamespace will be ignored when using addonTemplate to deploy the msa addon.
=> add addon deployment config

charts/managed-serviceaccount/templates/addontemplate.yaml, go.mod, go.sum
issue reference: https://github.com/open-cluster-management-io/ocm/issues/280
=> Update permission config in addontemplate

charts/managed-serviceaccount/templates/addontemplate.yaml, charts/managed-serviceaccount/templates/manager-deployment.yaml, pkg/addon/manager/manifests/templates/deployment.yaml
Fix: https://github.com/open-cluster-management-io/managed-serviceaccount/issues/84
=> Enable leader election only when the replica > 1

.github/workflows/go-release.yml
=> :seedling: Update github action for release

charts/managed-serviceaccount/templates/addontemplate.yaml, cmd/agent/main.go, pkg/addon/agent/controller/token.go, pkg/addon/agent/controller/token_test.go
=> ✨ Get token from secret when the apiserver does not have token request api

go.mod, go.sum
Fixes # https://github.com/open-cluster-management-io/ocm/issues/355
=> :seedling: upgrade addon-framework version

charts/managed-serviceaccount/Chart.yaml
=> :seedling: Update chart version to 0.5.0

.github/workflows/go-postsubmit.yml, .github/workflows/go-presubmit.yml, .github/workflows/go-release.yml
Add a workflow step that will create a PR to increase the chart version after a new release is created
Fixes #
=> :seedling: auto update chart version

.github/workflows/go-release.yml
=> 🌱 Use ocm bot token to create PR in release workflow

.github/workflows/pr-verify.yml
=> 🌱 Only verify PR title for main and release branch

charts/managed-serviceaccount/templates/addondeploymentconfig.yaml
=> 🌱 Use default agent install namespace

charts/managed-serviceaccount/templates/addondeploymentconfig.yaml, charts/managed-serviceaccount/templates/addontemplate.yaml, charts/managed-serviceaccount/templates/clustermanagementaddon.yaml
=> 🌱 Remove the default addondeploymentconfig

apis/authentication/v1beta1/managedserviceaccount_types.go, charts/managed-serviceaccount/crds/authentication.open-cluster-management.io_managedserviceaccounts.yaml, config/crd/bases/authentication.open-cluster-management.io_managedserviceaccounts.yaml, e2e/ephemeral_identity/ephemeral_identity.go, e2e/token/token.go
=> ⚠️ Deprecate managedserviceaccount rotation enabled field

charts/managed-serviceaccount/templates/addontemplate.yaml
Add label `addon.open-cluster-management.io/namespace: "true" ` to sync pull image secret from operator namespace to addon install namespace.
Fixes #
=> :seedling: add label to install namespace

charts/managed-serviceaccount/templates/clusterrole.yaml
=> 🐛 Update cluster-role

charts/managed-serviceaccount/Chart.yaml
=> 🌱 Update chart version to 0.6.0

pkg/addon/agent/controller/token.go, pkg/addon/agent/controller/token_test.go
=> 🐛 Check if the token has expired

charts/managed-serviceaccount/Chart.yaml
=> 🌱 Update chart version to 0.7.0

README.md
Fix the Helm repo URL in the README
Discovered and reported by community user: @stelucz in [Slack](https://kubernetes.slack.com/archives/C01GE7YSUUF/p1726639160633519).
Fixes #
=> :book: doc: fix helm repo URL in the README

cmd/manager/main.go, pkg/addon/agent/controller/token.go, pkg/addon/agent/controller/token_test.go
Fixes https://github.com/open-cluster-management-io/managed-serviceaccount/issues/119
=> 🐛 Use the real expire time to check if the token should refresh

.github/workflows/go-postsubmit.yml, .github/workflows/go-presubmit.yml, .github/workflows/go-release.yml, Dockerfile, Makefile, charts/managed-serviceaccount/templates/addontemplate.yaml, charts/managed-serviceaccount/templates/manager-deployment.yaml, cmd/agent/agent.go, cmd/main.go, cmd/manager/manager.go, go.mod, pkg/addon/manager/manifests/templates/deployment.yaml
Fixes #https://github.com/open-cluster-management-io/ocm/issues/363
=> 🌱 Merge manager and agent to one binary

.github/dependabot.yml
=> 🌱 Add dependabot to auto update dependencies

.github/workflows/go-presubmit.yml
```
Error: Codecov token not found. Please provide Codecov token with -t flag.
Warning: Codecov: Failed to properly create commit: The process '/home/runner/work/_actions/codecov/codecov-action/v4/dist/codecov' failed with exit code 1
```
Codecov fails to report coverage for a long time.
=> 🌱 Change coverage configuration

.github/workflows/chart-upload.yml, .github/workflows/go-release.yml, .github/workflows/increase-chart-version.yml
=> 🌱 Upload charts after the release published

.github/workflows/go-postsubmit.yml, .github/workflows/go-release.yml, Dockerfile
=> 🌱 upgrade base image to ubi9

README.md
=> :book: polish readme
